### ISSUE TITLE
Offline codec pack download problem

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint22.1-beta#76]
The problem of downloading an offline codec package, that is, if I use the apt download mint-meta-codecs command from the linux terminal with a net connection, it downloads an archive for installation without the Internet, but after I unzip and use that install.sh in the terminal, disconnecting the computer from the Internet name installs nothing probably doesn't download all dependencies in that offline archive...

**Comment by fblais** [comment]
Should be:
sudo apt **install** mint-meta-codecs
Not download.

**Comment by austincbrooks** [comment]
OP is referring to downloading mint-meta-codecs for use on an offline computer or LiveUSB session.  This process was officially described and supported in release notes prior to 22.0.  See:
https://linuxmint.com/rel_virginia.php

This process is useful to me too.  When I did the `sudo apt update && sudo download mint-meta-codecs` steps then unpacked the .tar.gz file and ran `./install.sh`, I got  a few errors:

W: Tried to start delayed item http://packages.linuxmint.com wilma/import amd64 libdvdcss2 amd64 1.4.2-dmo1, but failed
W: Tried to start delayed item http://archive.ubuntu.com/ubuntu noble/universe amd64 imagemagick-6-common all 8:6.9.12.98+dfsg1-5.2build2, but failed
W: Tried to start delayed item http://archive.ubuntu.com/ubuntu noble/universe amd64 timgm6mb-soundfont all 1.3-5, but failed

**Comment by ruldc** [comment]
Welcome Thank you very much for your support on this issue, it's really a
problem with downloading the offline codec packs in old linux versions
everything was perfect using the command apt download mint-meta-codecs it
downloads a complete archive for later use but now something happens in
these recent releases ,it's probably a problem that programmers can fix...
And one more bug I could say is when starting the computer from the moment
you press the power button and until that Linux mint logo appears it takes
about 15 seconds in the old versions of linux it was almost instant after
you press the power button or for example Windows 10 the boot logo appears
immediately...

mie., 25 dec. 2024, 01:48 Austin ***@***.***> a scris:

**Comment by ruldc** [comment]
I also tried copying from the var/cache/apt folder, but I still can't extract a complete list of codecs, the strange thing is that if you try to install from the linux menu, it's there in the multimedia section, where there is an option to install multimedia codecs, everything will recur normally, it installs all the dependencies are complete and everything works ok, but with the command apt download mint-meta-codecs an archive is downloaded but probably incomplete with all the dependencies trying to install that archive on the computer without having an internet connection it does not want to install, in the old mint versions, absolutely everything is downloaded for an internet-free use of codecs or even programs, for example, I also download vlc, openshot, audacity, brasero, gparted, gimp, etc. with that command from the terminal, it downloads them as archives and with that install, sh from the folder we ran in the terminal for installation, everything went normally, surely programmers can solve these problems, somewhere there is a problem, either conflicts between packages or tools, something happens, it's very bad that pulled from linux repository xplayer package was a good player thank you very much for understanding…

**Comment by clefebvre** [comment]
This is no longer supported/documented.

There is a regression in apt in Ubuntu 24.04 (which affects Mint22 and 22.1).

For some reason apt selects the online package instead of the local .deb.

You can see it when it says `Note, selecting 'x' instead of './x.deb'`.

It shouldn't do that but it does. This won't be worked on though, the ability for apt to install local debs isn't even something that is officially documented/supported either.

**Comment by clefebvre** [comment]
If you use `sudo dpkg -i *.deb` the local .deb files will get picked but then there's another problem... dpkg isn't smart and can't work around conflicts. `apt` can, `dpkg` cannot.

`dpkg` won't be able to temporarily remove `libavcodec` to install `libavcodec-extra`.

**Comment by clefebvre** [comment]
Fixed in mintsystem 8.6.2 by setting up a local repository in /etc/apt/sources.list.d/local.list.

**Comment by ruldc** [comment]
hello Clem
I have the beta version 22.1 and I put all the updates from the update manager then I used the terminal command to download the mint meta codecs package using the command apt download mint-meta-codecs and it downloads ok the archive but when I click on that install it does nothing. ..

Uploading simplescreenrecorder-2024-12-28_10.56.49.mp4…

**Comment by ruldc** [comment]
https://github.com/user-attachments/assets/22e89b18-2958-4822-9574-8ffff698761c

**Comment by clefebvre** [comment]
Run it from command line: `sudo ./install`

**Comment by ruldc** [comment]
I also ran this command above but it still doesn't work, using the terminal and using the command apt download mint-meta-codecs download that archive in the home folder but after unzipping and running that prompt install in the terminal it doesn't work, so the terminal instead to install those local deb files, try to download them from online servers, if you install everything online, codecs, programs, etc. work, but this method of downloading local deb packages of codecs was also good and the programs and to be able to install them very easily, you could even put them on a usb memory and use them with just a few clicks, it's a pity that Ubuntu has abandoned this necessary option as it is and in Windows you have offline programs for installation....

**Comment by ruldc** [comment]
from what I noticed, it downloads ok locally the .deb files of the program codecs in the archive, for example I use the following that are necessary for me: lie-meta-codec brazier openshot vlc player audacity gparted gimp etc., I usually use these programs, but there are a multitude of interesting programs in that list above, we download them all in archives, unzip them, and we had packages for each one separately, which we installed without internet in the terminal and they worked perfectly, for sure would be nice a method or program tool able to install these local .deb files linux is a powerful operating system thanks
